FROM python:3.12-slim

WORKDIR /app
# Копируем только необходимые файлы для воркера
COPY workers_depend/requirements.worker.txt .
RUN pip install --no-cache-dir -r requirements.worker.txt

# Копируем только нужные директории
COPY lib/queue ./lib/queue
COPY lib/crud ./lib/crud
COPY settings.py .

ENV RUN_MODE=worker
ENTRYPOINT ["python", "-m", "lib.queue.worker"]