"""add error counter

Revision ID: 17b979d42608
Revises: 8f8fdae8f8d6
Create Date: 2025-03-23 12:52:20.470325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b979d42608'
down_revision: Union[str, None] = '8f8fdae8f8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('subject', sa.String(length=255), nullable=True))
    op.add_column('notifications', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('last_error', sa.Text(), nullable=True))
    op.drop_column('notifications', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'last_error')
    op.drop_column('notifications', 'retry_count')
    op.drop_column('notifications', 'body')
    op.drop_column('notifications', 'subject')

    # ### end Alembic commands ###
